#include "videosourcefactory.h"
#include "videotargetfactory.h"
#include "except.h"
#include "iobservable.h"
#include "gil.h"
#ifdef USE_OPENCV
#include "opencv_video_source.h"
#include "opencv_video_target.h"
#endif // USE_OPENCV
#ifdef USE_EPIPHANSDK
#include "epiphansdk_video_source.h"
#endif
#ifdef USE_LIBVLC
#include "vlc_video_source.h"
#endif
#ifdef USE_FFMPEG
#include "ffmpeg_video_target.h"
#endif
#include <boost/python.hpp>
#include <boost/python/exception_translator.hpp>
#ifdef USE_NUMPY
#include <boost/python/numpy.hpp>
#endif

using namespace boost::python;

class VideoFrameNumPyWrapper : public gg::VideoFrame, public wrapper<gg::VideoFrame>
{
public:
    //!
    //! \brief
    //! \param rhs
    //!
    VideoFrameNumPyWrapper(const gg::VideoFrame & rhs)
        : gg::VideoFrame(rhs)
    {
        // nop
    }

    //!
    //! \brief
    //! \param colour
    //! \param cols
    //! \param rows
    //!
    VideoFrameNumPyWrapper(enum gg::ColourSpace colour, size_t cols, size_t rows)
        : gg::VideoFrame(colour, cols, rows)
    {
        // nop
    }

    //!
    //! \brief
    //! \param colour
    //! \param manage_data
    //!
    VideoFrameNumPyWrapper(enum gg::ColourSpace colour, bool manage_data)
        : gg::VideoFrame(colour, manage_data)
    {
        // nop
    }

#ifdef USE_NUMPY
    //!
    //! \brief Create a NumPy array referencing gg::VideoFrame::data()
    //! \return
    //!
    boost::python::numpy::ndarray data_as_ndarray()
    {
        return boost::python::numpy::from_data(
                    this->data(),
                    boost::python::numpy::dtype::get_builtin<uint8_t>(),
                    // shape
                    boost::python::make_tuple(data_length()),
                    // stride, i.e. 1 byte to go to next entry in this case
                    boost::python::make_tuple(sizeof(uint8_t)),
                    // owner (dangerous to pass None)
                    boost::python::object()
               );
    }
#endif
};

class IObservableWrapper : public gg::IObservable, public wrapper<gg::IObservable>
{
public:
    void attach(gg::IObserver & observer)
    {
        if (override f = this->get_override("attach"))
            f(boost::ref(observer));
        else
            gg::IObservable::attach(boost::ref(observer));
    }

    void default_attach(gg::IObserver & observer)
    {
        gg::IObservable::attach(boost::ref(observer));
    }

    void detach(gg::IObserver & observer)
    {
        if (override f = this->get_override("detach"))
            f(boost::ref(observer));
        else
            gg::IObservable::detach(boost::ref(observer));
    }

    void default_detach(gg::IObserver & observer)
    {
        gg::IObservable::detach(boost::ref(observer));
    }
};

class IVideoSourceWrapper : public IVideoSource, public wrapper<IVideoSource>
{
public:
    bool get_frame_dimensions(int & width, int & height)
    {
        return this->get_override("get_frame_dimensions")(width, height);
    }

    bool get_frame(gg::VideoFrame & frame)
    {
        return this->get_override("get_frame")(frame);
    }

    double get_frame_rate()
    {
        return this->get_override("get_frame_rate")();
    }

    void set_sub_frame(int x, int y, int width, int height)
    {
        this->get_override("set_sub_frame")(x, y, width, height);
    }

    void get_full_frame()
    {
        this->get_override("get_full_frame")();
    }
};

/* The inheritance should be public, in order to preserve
 * the public accessibility of the update() method. The
 * Boost.Python examples feature struct's rather than
 * classes, and in struct's everything is public by
 * definition.
 */
class IObserverWrapper : public gg::IObserver, public wrapper<gg::IObserver>
{
public:
    IObserverWrapper()
    {
        /* Default constructor that needs to be called within
         * child Python class, e.g. super(Child, self).__init__()
         * This is normally generated by the compiler
         * automatically, but we define it here explicitly so
         * that it can serve as an example for this complex case.
         */
    }

    void update(gg::VideoFrame & frame)
    {
        gg::ScopedPythonGILLock gil_lock;
        this->get_override("update")(boost::ref(frame));
    }
};

class IVideoTargetWrapper : public gg::IVideoTarget, public wrapper<gg::IVideoTarget>
{
public:
    void append(const gg::VideoFrame & frame)
    {
        this->get_override("append")(frame);
    }
};

void translate_VideoSourceError(gg::VideoSourceError const & e)
{
    std::string msg;
    msg.append("VideoSourceError: ").append(e.what());
    PyErr_SetString(PyExc_RuntimeError, msg.c_str());
}

void translate_DeviceAlreadyConnected(gg::DeviceAlreadyConnected const & e)
{
    std::string msg;
    msg.append("DeviceAlreadyConnected: ").append(e.what());
    PyErr_SetString(PyExc_IOError, msg.c_str());
}

void translate_DeviceNotFound(gg::DeviceNotFound const & e)
{
    std::string msg;
    msg.append("DeviceNotFound: ").append(e.what());
    PyErr_SetString(PyExc_IOError, msg.c_str());
}

void translate_DeviceOffline(gg::DeviceOffline const & e)
{
    std::string msg;
    msg.append("DeviceOffline: ").append(e.what());
    PyErr_SetString(PyExc_IOError, msg.c_str());
}

void translate_VideoTargetError(gg::VideoTargetError const & e)
{
    std::string msg;
    msg.append("VideoTargetError: ").append(e.what());
    PyErr_SetString(PyExc_RuntimeError, msg.c_str());
}

void translate_ObserverError(gg::ObserverError const & e)
{
    std::string msg;
    msg.append("ObserverError: ").append(e.what());
    PyErr_SetString(PyExc_RuntimeError, msg.c_str());
}

BOOST_PYTHON_MODULE(pygiftgrab)
{
    PyEval_InitThreads();
#ifdef USE_NUMPY
    boost::python::numpy::initialize();
#endif

    register_exception_translator<gg::VideoSourceError>(&translate_VideoSourceError);
    register_exception_translator<gg::DeviceAlreadyConnected>(&translate_DeviceAlreadyConnected);
    register_exception_translator<gg::DeviceNotFound>(&translate_DeviceNotFound);
    register_exception_translator<gg::DeviceOffline>(&translate_DeviceOffline);
    register_exception_translator<gg::VideoTargetError>(&translate_VideoTargetError);
    register_exception_translator<gg::ObserverError>(&translate_ObserverError);

    enum_<gg::ColourSpace>("ColourSpace")
        .value("BGRA", gg::ColourSpace::BGRA)
        .value("I420", gg::ColourSpace::I420)
    ;

    enum_<gg::Device>("Device")
        .value("DVI2PCIeDuo_SDI", gg::Device::DVI2PCIeDuo_SDI)
        .value("DVI2PCIeDuo_DVI", gg::Device::DVI2PCIeDuo_DVI)
    ;

    enum_<gg::Codec>("Codec")
        .value("HEVC", gg::Codec::HEVC)
        .value("Xvid", gg::Codec::Xvid)
        .value("VP9", gg::Codec::VP9)
    ;

    class_<VideoFrameNumPyWrapper>("VideoFrame", init<enum gg::ColourSpace, bool>())
        .def(init<enum gg::ColourSpace, const size_t, const size_t>())
        .def("rows", &VideoFrameNumPyWrapper::rows)
        .def("cols", &VideoFrameNumPyWrapper::cols)
        .def("data_length", &VideoFrameNumPyWrapper::data_length)
#ifdef USE_NUMPY
        .def("data", &VideoFrameNumPyWrapper::data_as_ndarray)
#endif
    ;

    class_<IObservableWrapper, boost::noncopyable>("IObservable", no_init)
        .def("attach", &IObservableWrapper::attach)
        .def("detach", &IObservableWrapper::detach)
    ;

    class_<IVideoSource, bases<gg::IObservable>, boost::noncopyable>(
                "IVideoSource", no_init)
    ;

#ifdef USE_OPENCV
    class_<VideoSourceOpenCV, bases<IVideoSource>, boost::noncopyable>(
                "VideoSourceOpenCV", init<int>())
        .def(init<char *>())
        .def("get_frame", &VideoSourceOpenCV::get_frame)
        .def("get_frame_dimensions", &VideoSourceOpenCV::get_frame_dimensions)
        .def("get_frame_rate", &VideoSourceOpenCV::get_frame_rate)
        .def("set_sub_frame", &VideoSourceOpenCV::set_sub_frame)
        .def("get_full_frame", &VideoSourceOpenCV::get_full_frame)
        .def("attach", &gg::IObservable::attach, &IObservableWrapper::default_attach)
        .def("detach", &gg::IObservable::detach, &IObservableWrapper::default_detach)
    ;
#endif // USE_OPENCV

#ifdef USE_EPIPHANSDK
    class_<gg::VideoSourceEpiphanSDK, bases<IVideoSource>, boost::noncopyable>(
                "VideoSourceEpiphanSDK", init<const std::string, const V2U_INT32>())
        .def("get_frame", &gg::VideoSourceEpiphanSDK::get_frame)
        .def("get_frame_dimensions", &gg::VideoSourceEpiphanSDK::get_frame_dimensions)
        .def("get_frame_rate", &gg::VideoSourceEpiphanSDK::get_frame_rate)
        .def("set_sub_frame", &gg::VideoSourceEpiphanSDK::set_sub_frame)
        .def("get_full_frame", &gg::VideoSourceEpiphanSDK::get_full_frame)
        .def("attach", &gg::IObservable::attach, &IObservableWrapper::default_attach)
        .def("detach", &gg::IObservable::detach, &IObservableWrapper::default_detach)
    ;
#endif

#ifdef USE_LIBVLC
    class_<gg::VideoSourceVLC, bases<IVideoSource>, boost::noncopyable>(
                "VideoSourceVLC", init<const std::string>())
        .def("get_frame", &gg::VideoSourceVLC::get_frame)
        .def("get_frame_dimensions", &gg::VideoSourceVLC::get_frame_dimensions)
        .def("get_frame_rate", &gg::VideoSourceVLC::get_frame_rate)
        .def("set_sub_frame", &gg::VideoSourceVLC::set_sub_frame)
        .def("get_full_frame", &gg::VideoSourceVLC::get_full_frame)
        .def("attach", &gg::IObservable::attach, &IObservableWrapper::default_attach)
        .def("detach", &gg::IObservable::detach, &IObservableWrapper::default_detach)
    ;
#endif

    class_<IObserverWrapper, boost::noncopyable>("IObserver")
        .def("update", pure_virtual(&gg::IObserver::update))
    ;

    class_<gg::IVideoTarget, bases<gg::IObserver>, boost::noncopyable>(
                "IVideoTarget", no_init)
        .def("update", &gg::IVideoTarget::update)
    ;

#ifdef USE_FFMPEG
    class_<gg::VideoTargetFFmpeg, bases<gg::IVideoTarget>, boost::noncopyable>(
                "VideoTargetFFmpeg", init<std::string, std::string, float>())
        .def("append", &gg::VideoTargetFFmpeg::append)
    ;
#endif

#ifdef USE_OPENCV
    class_<gg::VideoTargetOpenCV, bases<gg::IVideoTarget>, boost::noncopyable>(
                "VideoTargetOpenCV", init<std::string, std::string, float>())
        .def("append", &gg::VideoTargetOpenCV::append)
    ;
#endif // USE_OPENCV

    class_<gg::VideoSourceFactory, boost::noncopyable>("VideoSourceFactory", no_init)
        .def("get_device", &gg::VideoSourceFactory::get_device
             /* Keep returned pointer (0) alive as long as factory (1) alive.
              * Boost.Python documentation says reference_existing_object is
              * dangerous, but apparently only when no additional lifetime
              * management with a call policy is provided (for details, see:
              * http://www.boost.org/doc/libs/1_39_0/libs/python/doc/v2/reference_existing_object.html
              * ).
              */
             , return_value_policy<reference_existing_object, with_custodian_and_ward_postcall<1, 0> >()
        )
        .def("free_device", &gg::VideoSourceFactory::free_device)
        .def("get_instance", &gg::VideoSourceFactory::get_instance
             , return_value_policy<reference_existing_object>()
        )
        .staticmethod("get_instance")
    ;

    class_<gg::VideoTargetFactory, boost::noncopyable>("VideoTargetFactory", no_init)
        .def("create_file_writer", &gg::VideoTargetFactory::create_file_writer,
             /* We use manage_new_object here in order
              * to give ownership is to client. Also
              * this ensures that the newly created
              * object will be destroyed as part of the
              * Python object destruction procedure. See
              * https://wiki.python.org/moin/boost.python/CallPolicy#manage_new_object
              */
             return_value_policy<manage_new_object>()
        )
        .def("get_instance", &gg::VideoTargetFactory::get_instance
             , return_value_policy<reference_existing_object>()
        )
        .staticmethod("get_instance")
    ;
}
